name: insta_assets_crop_example
description: Demonstrates how to use the insta_assets_crop plugin.

version: 0.0.1+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  insta_assets_crop:
    path: ../

flutter:
  uses-material-design: true
