name: insta_assets_crop_example
description: Demonstrates how to use the insta_assets_crop plugin.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+2

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  insta_assets_crop:
    path: ../

flutter:
  uses-material-design: true
